[tools]

# language runtimes (fine)
go = "1.26.0"
rust = "stable"
python = "3.14"
uv = "latest"
lua = "5.1"

# rust tools
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:bat" = "latest"
"cargo:duf" = "latest"
"cargo:just" = "latest"
"cargo:zoxide" = "latest"
"cargo:git-delta" = "latest"
"cargo:btop" = "latest"
"cargo:television" = "latest"
"cargo:diskonaut" = "latest"

# python tools
"uvx:ruff" = "latest"
"uvx:black" = "latest"
"uvx:dotbot" = "latest"
"uvx:pre-commit" = "latest"
"uvx:pyright" = "latest"


# go tools
"go:github.com/rshelekhov/lazymake/cmd/lazymake" = "latest"
"go:github.com/maaslalani/nap" = "latest"
"go:github.com/pashkov256/deletor" = "latest"
"go:github.com/Gu1llaum-3/sshm" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
# unavoidable github
neovim = "0.11.5"
tmux = "latest"
github-cli = "2.85.0"
jq = "latest"
fzf = "latest"
