[tools]
go = "1.26.0"
rust = "stable"
python = "3.14"
uv = "latest"
neovim = "0.11.5"

ripgrep = "latest"
fd = "latest"
bat = "latest"
duf = "latest"
direnv = "2.37.1"
just = "1.46.0"
fzf = "latest"
tmux = "latest"
github-cli = "2.85.0"
jq = "1.8.1"
zoxide = "latest"
btop = "latest"

yq = "4.50.1"
delta = "latest"
lazydocker = "latest"
television = "latest"
glow = "latest"
opencode = "latest"
crush = "latest"
ruff = "latest"
black = "latest"

"go:github.com/rshelekhov/lazymake/cmd/lazymake" = "latest"
"go:github.com/maaslalani/nap" = "latest"
"go:github.com/pashkov256/deletor" = "latest"
"go:github.com/Gu1llaum-3/sshm" = "latest"
"cargo:serie" = "latest"
"cargo:broot" = "latest"
